language: java
jdk:
  - openjdk8

dist: trusty
sudo: required

branches:
  only:
  - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get update -q
  - curl -sLO https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.5-1.trusty_amd64.deb

script:
  - ./gradlew clean build


